import { Question } from "../../quiz";

export const cs224rLecture1IntroQuestions: Question[] = [
  // ============================================================
  // CS224R – Lecture 1: Introduction to Deep Reinforcement Learning
  // Q1–Q35
  // ============================================================

  // ============================================================
  // Introductory formulation questions
  // ============================================================

  {
    id: "cs224r-lect1-q36",
    chapter: 1,
    difficulty: "easy",
    prompt:
      "A music recommender chooses a song, observes whether the user keeps listening, and then chooses the next song. Which statements explain why this can be framed as a reinforcement learning problem?",
    options: [
      {
        text: "The recommendation is an action that can change later observations and user feedback.",
        isCorrect: true,
      },
      {
        text: "The system receives an objective signal rather than a label for the one correct song at each step.",
        isCorrect: true,
      },
      {
        text: "The data distribution can evolve because earlier recommendations affect later contexts over steps.",
        isCorrect: true,
      },
      {
        text: "The system can learn from experience rather than only from fixed labeled examples.",
        isCorrect: true,
      },
    ],
    explanation:
      "The recommender is making sequential decisions: one action affects what the user hears and how future feedback is generated. That differs from ordinary supervised learning because the data distribution can depend on the system's choices and the feedback can be an objective signal rather than a direct label.",
  },

  {
    id: "cs224r-lect1-q37",
    chapter: 1,
    difficulty: "easy",
    prompt:
      "A robot controller uses a policy written as \\(\\pi_\\theta(a \\mid s)\\). Which statements correctly distinguish the policy from the environment dynamics and reward?",
    options: [
      {
        text: "The policy selects or samples actions from the current state or observation.",
        isCorrect: true,
      },
      {
        text: "Changing policy parameters can change which trajectories the agent visits.",
        isCorrect: true,
      },
      {
        text: "The policy can be represented by a neural network that outputs action probabilities.",
        isCorrect: true,
      },
      {
        text: "The policy is distinct from both the transition model and the reward function.",
        isCorrect: true,
      },
    ],
    explanation:
      "The policy represents behavior: it maps what the agent knows to actions, often as a distribution parameterized by a neural network. The dynamics describe how the world changes after an action, and the reward function scores outcomes, so those pieces play different roles in the RL objective.",
  },

  {
    id: "cs224r-lect1-q38",
    chapter: 1,
    difficulty: "easy",
    prompt:
      "A rollout is represented as \\(\\tau=(s_1,a_1,\\ldots,s_T,a_T)\\). Which statements correctly describe this trajectory representation?",
    options: [
      {
        text: "It records the temporal sequence of states or observations and actions.",
        isCorrect: true,
      },
      {
        text: "It is generated by alternating policy action choices with environment transitions.",
        isCorrect: true,
      },
      {
        text: "It can be augmented with rewards when computing the return for the episode.",
        isCorrect: true,
      },
      {
        text: "It must be identical every time the same policy is rolled out in the same task.",
        isCorrect: false,
      },
    ],
    explanation:
      "A trajectory is the data record produced by executing a policy through time, and rewards can be attached to that record when evaluating performance. Even with the same policy, stochastic actions, stochastic dynamics, or changing initial conditions can make different rollouts differ.",
  },

  {
    id: "cs224r-lect1-q39",
    chapter: 1,
    difficulty: "medium",
    prompt:
      "A towel-hanging robot uses \\(s_t\\) to include the arm pose, towel pose, and hook pose. Which statement would be evidence that this representation is not really Markov?",
    options: [
      {
        text: "Predicting the next towel pose also requires an earlier hidden contact event that is not encoded in \\(s_t\\).",
        isCorrect: true,
      },
      {
        text: "The next state is sampled from a transition distribution rather than computed deterministically, because the world can be stochastic.",
        isCorrect: false,
      },
      {
        text: "A policy uses only the current state as input instead of receiving the complete history.",
        isCorrect: false,
      },
      {
        text: "The state-action sequence can be written as a trajectory for later learning or evaluation.",
        isCorrect: false,
      },
    ],
    explanation:
      "The Markov property says the current state and action are sufficient for predicting the next-state distribution. Stochastic dynamics and policies are compatible with that property, but an unencoded past event that still affects the future means the chosen representation is missing state information.",
  },

  {
    id: "cs224r-lect1-q40",
    chapter: 1,
    difficulty: "medium",
    prompt:
      "A self-driving system receives a current camera and LiDAR snapshot, but the snapshot alone does not reveal nearby cars' velocities. Which statements explain why observation history may be useful?",
    options: [
      {
        text: "A single observation can omit information needed to predict what happens next.",
        isCorrect: true,
      },
      {
        text: "A short history can help infer hidden variables such as velocity from changes over time.",
        isCorrect: true,
      },
      {
        text: "An observation is what the agent directly receives, even when it is not a complete state.",
        isCorrect: true,
      },
      {
        text: "A policy with memory can use several observations when the current one is partial.",
        isCorrect: true,
      },
    ],
    explanation:
      "Observations are what the agent directly receives, and they may be partial views of the true state. History can make the policy's input closer to a useful state representation, especially when velocity or other hidden variables must be inferred over time.",
  },

  {
    id: "cs224r-lect1-q41",
    chapter: 1,
    difficulty: "medium",
    prompt:
      "A robot receives reward \\(1\\) only when a towel is on a hook and \\(0\\) otherwise. Which statements correctly describe this reward design?",
    options: [
      {
        text: "It specifies the task objective without directly labeling every correct action.",
        isCorrect: true,
      },
      {
        text: "It can make early learning difficult if successful trajectories are rarely observed.",
        isCorrect: true,
      },
      {
        text: "It can depend on the state, the action, or both, depending on how the task is modeled.",
        isCorrect: true,
      },
      {
        text: "It may need demonstrations, shaping, or exploration support when success is rarely observed.",
        isCorrect: true,
      },
    ],
    explanation:
      "The reward says what outcome is desirable, not which action should be chosen at each step. A sparse 0-or-1 signal may provide little guidance until the agent sees some success, which is why demonstrations, shaping, or better exploration can matter.",
  },

  {
    id: "cs224r-lect1-q42",
    chapter: 1,
    difficulty: "hard",
    prompt:
      "For \\(p_\\theta(\\tau)=p(s_1)\\prod_t \\pi_\\theta(a_t \\mid s_t)p(s_{t+1} \\mid s_t,a_t)\\), which statements correctly connect trajectory probabilities to the RL objective?",
    options: [
      {
        text: "Policy parameters affect expected return by changing the distribution over trajectories.",
        isCorrect: true,
      },
      {
        text: "The objective averages cumulative reward over trajectories induced by policy and dynamics.",
        isCorrect: true,
      },
      {
        text: "Reward values must be multiplied into \\(p_\\theta(\\tau)\\) as transition probabilities.",
        isCorrect: false,
      },
      {
        text: "The policy is optimized as a fixed-label predictor whose outputs cannot affect later states.",
        isCorrect: false,
      },
    ],
    explanation:
      "The policy appears in the objective through the trajectory distribution: different action probabilities make different futures more or less likely. Rewards are summed along sampled trajectories to define return, but they are not themselves transition-probability factors in this state-action trajectory model.",
  },

  {
    id: "cs224r-lect1-q43",
    chapter: 1,
    difficulty: "hard",
    prompt:
      "Which statements identify source-backed reasons to use a stochastic policy rather than a deterministic mapping from state to one action?",
    options: [
      {
        text: "Sampling different actions can support exploration while learning from experience.",
        isCorrect: true,
      },
      {
        text: "A distribution over actions can model varied behavior seen in collected data.",
        isCorrect: true,
      },
      {
        text: "A stochastic policy assigns probabilities to actions rather than choosing only one fixed action.",
        isCorrect: true,
      },
      {
        text: "Generative models over actions can be useful when behavior data contains variation across demos.",
        isCorrect: true,
      },
    ],
    explanation:
      "The lecture motivates stochastic policies both for exploration and for modeling behavior that varies across people or systems. In this framing, the policy is a distribution over actions, which makes generative action models relevant for reinforcement learning and imitation learning.",
  },

  {
    id: "cs224r-lect1-q44",
    chapter: 1,
    difficulty: "hard",
    prompt:
      "Which statements correctly distinguish \\(V^\\pi(s)\\) and \\(Q^\\pi(s,a)\\) from the immediate reward function?",
    options: [
      {
        text: "\\(V^\\pi(s)\\) estimates future expected reward starting at \\(s\\) and then following \\(\\pi\\).",
        isCorrect: true,
      },
      {
        text: "\\(Q^\\pi(s,a)\\) evaluates taking \\(a\\) first and then following \\(\\pi\\).",
        isCorrect: true,
      },
      {
        text: "Both functions are simply aliases for the one-step reward \\(r(s,a)\\).",
        isCorrect: false,
      },
      {
        text: "Both functions are independent of the policy used after the current state or action is chosen.",
        isCorrect: false,
      },
    ],
    explanation:
      "Value functions summarize long-term consequences under a policy, so they are not just immediate rewards. The state value starts from a state and follows the policy, while the Q-function fixes the first action before continuing with the policy.",
  },

  // ============================================================
  // Q10–Q18: EXACTLY 3 TRUE
  // ============================================================

  {
    id: "cs224r-lect1-q10",
    chapter: 1,
    difficulty: "easy",
    prompt:
      "Which statements about supervised learning versus reinforcement learning are correct?",
    options: [
      {
        text: "Supervised learning typically uses labeled input–output pairs.",
        isCorrect: true,
      },
      {
        text: "Reinforcement learning feedback is often delayed.",
        isCorrect: true,
      },
      {
        text: "Reinforcement learning data is not independent and identically distributed.",
        isCorrect: true,
      },
      {
        text: "Supervised learning requires interaction with an environment before each training label is produced.",
        isCorrect: false,
      },
    ],
    explanation:
      "Supervised learning usually trains on labeled input-output pairs, so the target output is supplied directly. Reinforcement learning instead learns from experience and objective feedback, often after a delay, and the agent's actions influence which states and observations appear later. That feedback loop is why reinforcement learning data is not independent and identically distributed, and why supervised learning does not require environment interaction before each label exists.",
  },

  {
    id: "cs224r-lect1-q11",
    chapter: 1,
    difficulty: "medium",
    prompt: "Which statements about Markov Decision Processes are correct?",
    options: [
      {
        text: "They consist of states, actions, rewards, and dynamics.",
        isCorrect: true,
      },
      { text: "They assume the Markov property holds.", isCorrect: true },
      {
        text: "They define a probability distribution over trajectories.",
        isCorrect: true,
      },
      {
        text: "They require full observability of the environment.",
        isCorrect: false,
      },
    ],
    explanation:
      "A Markov Decision Process specifies the state space, action space, reward function, and transition dynamics used to model sequential decisions. The Markov property is the key assumption: the current state and action are sufficient for the next-state distribution, which induces a distribution over trajectories when combined with a policy. If the agent only receives incomplete observations, the problem is better treated as partially observable rather than assuming the visible observation is automatically the full state.",
  },

  {
    id: "cs224r-lect1-q12",
    chapter: 1,
    difficulty: "medium",
    prompt: "Which statements about observations are correct?",
    options: [
      {
        text: "They may require maintaining a history to infer the state.",
        isCorrect: true,
      },
      {
        text: "They are always equivalent to the true state.",
        isCorrect: false,
      },
      { text: "They can come from sensors or user inputs.", isCorrect: true },
      {
        text: "They can lead to partially observable problems.",
        isCorrect: true,
      },
    ],
    explanation:
      "An observation is the signal the agent directly receives, such as a sensor reading, image, user message, or other input. It can be less informative than the true state, so a policy may need history or memory to infer hidden quantities like velocity or conversation context. Treating observations as always identical to the state misses the lecture's distinction between full state information and partial observability.",
  },

  {
    id: "cs224r-lect1-q13",
    chapter: 1,
    difficulty: "medium",
    prompt: "Which statements about trajectories are correct?",
    options: [
      {
        text: "They depend on both the policy and environment dynamics.",
        isCorrect: true,
      },
      { text: "They are deterministic given a policy.", isCorrect: false },
      { text: "They can be used as training data.", isCorrect: true },
      {
        text: "They represent experience collected by the agent.",
        isCorrect: true,
      },
    ],
    explanation:
      "A trajectory records the time-ordered experience produced as the policy chooses actions and the environment responds. Because the policy may sample actions and the dynamics may be stochastic, rolling out the same policy does not have to produce the same trajectory every time. Those collected trajectories are training data for reinforcement learning, but they are generated by interaction rather than by independent labeled examples.",
  },

  {
    id: "cs224r-lect1-q14",
    chapter: 1,
    difficulty: "hard",
    prompt:
      "Which statements about stochasticity in reinforcement learning are correct?",
    options: [
      { text: "Environment transitions can be stochastic.", isCorrect: true },
      {
        text: "Policies can introduce randomness in action selection.",
        isCorrect: true,
      },
      { text: "Stochasticity affects expected returns.", isCorrect: true },
      { text: "Stochasticity makes learning impossible.", isCorrect: false },
    ],
    explanation:
      "Reinforcement learning objectives are usually expectations because both the world and the policy can introduce randomness. A stochastic transition model means the same state-action pair can lead to different next states, and a stochastic policy can intentionally sample different actions. This uncertainty changes expected return, but it does not make learning impossible; it means algorithms must estimate and optimize performance over a distribution of outcomes.",
  },

  {
    id: "cs224r-lect1-q15",
    chapter: 1,
    difficulty: "hard",
    prompt: "Which statements about discount factors are correct?",
    options: [
      {
        text: "They weight future rewards relative to immediate rewards.",
        isCorrect: true,
      },
      {
        text: "A discount factor of 1 treats all rewards equally.",
        isCorrect: true,
      },
      {
        text: "Smaller discount factors emphasize near-term rewards.",
        isCorrect: true,
      },
      {
        text: "Discount factors eliminate the need for value functions.",
        isCorrect: false,
      },
    ],
    explanation:
      "A discount factor weights rewards by how far in the future they occur, so it changes the tradeoff between immediate and delayed outcomes. When the factor is 1, future rewards are weighted the same as immediate rewards; smaller values make near-term rewards matter more. Discounting does not remove the need for value functions, because value functions still estimate expected future return under the chosen weighting.",
  },

  {
    id: "cs224r-lect1-q16",
    chapter: 1,
    difficulty: "medium",
    prompt:
      "Which statements about policies parameterized by neural networks are correct?",
    options: [
      {
        text: "They can process high-dimensional inputs like images.",
        isCorrect: true,
      },
      {
        text: "They can be trained using gradient-based methods.",
        isCorrect: true,
      },
      { text: "They require labeled action targets.", isCorrect: false },
      {
        text: "They are common in deep reinforcement learning.",
        isCorrect: true,
      },
    ],
    explanation:
      "A neural network policy is a parameterized mapping from states or observations to actions, or to a distribution over actions. Neural networks are useful in deep reinforcement learning because they can process high-dimensional inputs such as images and can be optimized with gradient-based methods. The learning signal does not have to be a labeled action target; reinforcement learning can train behavior from rewards or returns instead.",
  },

  {
    id: "cs224r-lect1-q17",
    chapter: 1,
    difficulty: "hard",
    prompt: "Which statements about value functions are correct?",
    options: [
      {
        text: "They estimate expected future reward under a policy.",
        isCorrect: true,
      },
      {
        text: "They depend on the dynamics of the environment.",
        isCorrect: true,
      },
      { text: "They can be used to improve policies.", isCorrect: true },
      { text: "They eliminate the need for exploration.", isCorrect: false },
    ],
    explanation:
      "A value function estimates expected future reward when the agent starts from a state, or from a state-action pair, and then follows a policy. Its estimate depends on the policy, the reward function, and the environment dynamics because all of those shape future trajectories. Values can guide policy improvement, but they do not eliminate exploration because the agent may still need experience to learn which actions and states have high value.",
  },

  {
    id: "cs224r-lect1-q18",
    chapter: 1,
    difficulty: "easy",
    prompt:
      "Which statements about reinforcement learning applications are correct?",
    options: [
      { text: "They include robotics and control tasks.", isCorrect: true },
      { text: "They include game playing.", isCorrect: true },
      { text: "They include language model post-training.", isCorrect: true },
      { text: "They are limited to simulated environments.", isCorrect: false },
    ],
    explanation:
      "The lecture uses robotics, control, games, and language model post-training as examples where decisions have consequences and feedback can be optimized over time. Simulation is often useful because it makes experience cheaper and safer to collect, but reinforcement learning is not limited to simulated worlds. Real robots, recommendation systems, traffic systems, and human-facing AI systems can also be modeled as sequential decision problems.",
  },

  // ============================================================
  // Q19–Q27: EXACTLY 2 TRUE
  // ============================================================

  {
    id: "cs224r-lect1-q19",
    chapter: 1,
    difficulty: "easy",
    prompt:
      "Which statements correctly describe actions in reinforcement learning?",
    options: [
      { text: "They are decisions made by the agent.", isCorrect: true },
      { text: "They influence future states.", isCorrect: true },
      { text: "They are always discrete.", isCorrect: false },
      { text: "They are independent of the policy.", isCorrect: false },
    ],
    explanation:
      "Actions are the decisions the agent makes, such as moving a robot arm, recommending a song, or choosing a response. They matter because the current action can change the next state or observation, which then changes later experience. Action spaces can be discrete or continuous, and actions are not independent of the policy because the policy is the rule or distribution that selects them.",
  },

  {
    id: "cs224r-lect1-q20",
    chapter: 1,
    difficulty: "medium",
    prompt:
      "Which statements about partially observable Markov decision processes are correct?",
    options: [
      {
        text: "They arise when the agent cannot observe the full state.",
        isCorrect: true,
      },
      { text: "They often require memory or belief states.", isCorrect: true },
      {
        text: "They assume the Markov property over observations.",
        isCorrect: false,
      },
      { text: "They remove the need for policies.", isCorrect: false },
    ],
    explanation:
      "A partially observable Markov decision process arises when the agent receives observations that do not contain all state information needed for prediction and control. Memory, belief states, or a history of observations can help recover hidden variables, such as velocity from consecutive sensor readings. The raw observation itself is not assumed to be Markov, and the agent still needs a policy for choosing actions under uncertainty.",
  },

  {
    id: "cs224r-lect1-q21",
    chapter: 1,
    difficulty: "medium",
    prompt: "Which statements about trajectories are correct?",
    options: [
      { text: "They can include both states and actions.", isCorrect: true },
      { text: "They always have fixed length.", isCorrect: false },
      { text: "They are equivalent to supervised datasets.", isCorrect: false },
      { text: "They represent sequences over time.", isCorrect: true },
    ],
    explanation:
      "A trajectory is a sequence over time, commonly written as alternating states or observations and actions. Its length can depend on the task horizon, termination condition, or episode definition, so it does not always have a fixed length. It is not equivalent to a supervised dataset because the samples are temporally linked and generated by the policy interacting with environment dynamics.",
  },

  {
    id: "cs224r-lect1-q22",
    chapter: 1,
    difficulty: "hard",
    prompt: "Which statements about reward design are correct?",
    options: [
      { text: "Sparse rewards can make learning difficult.", isCorrect: true },
      { text: "Reward shaping can help guide learning.", isCorrect: true },
      { text: "Rewards must always be differentiable.", isCorrect: false },
      { text: "Rewards uniquely determine optimal actions.", isCorrect: false },
    ],
    explanation:
      "Sparse rewards can make early learning difficult because the agent may see many unsuccessful trajectories with little signal about how to improve. Reward shaping can add intermediate feedback that points learning toward useful behavior, as long as it is designed carefully. Rewards do not have to be differentiable, and they do not uniquely determine a single optimal action because dynamics, state, stochasticity, and ties between behaviors can all matter.",
  },

  {
    id: "cs224r-lect1-q23",
    chapter: 1,
    difficulty: "hard",
    prompt: "Which statements about expected return are correct?",
    options: [
      {
        text: "It averages rewards over possible trajectories.",
        isCorrect: true,
      },
      { text: "It depends on the policy.", isCorrect: true },
      { text: "It ignores stochasticity.", isCorrect: false },
      { text: "It is identical to immediate reward.", isCorrect: false },
    ],
    explanation:
      "Expected return averages cumulative reward over the trajectory distribution induced by the policy, the initial state distribution, and the environment dynamics. It depends on the policy because changing action probabilities changes which futures are likely. It explicitly handles stochasticity through the expectation, and it is broader than immediate reward because it evaluates reward accumulated over time.",
  },

  {
    id: "cs224r-lect1-q24",
    chapter: 1,
    difficulty: "easy",
    prompt: "Which statements about reinforcement learning data are correct?",
    options: [
      { text: "It is generated through interaction.", isCorrect: true },
      {
        text: "It is independent and identically distributed.",
        isCorrect: false,
      },
      { text: "It reflects the agent’s current policy.", isCorrect: true },
      { text: "It never changes over time.", isCorrect: false },
    ],
    explanation:
      "Reinforcement learning data is collected through interaction, so the agent's current policy helps determine which states, actions, and rewards appear in the dataset. As the policy changes, the data distribution can change too, because different actions lead to different future observations. That dependence is why the data is not independent and identically distributed and why it is wrong to treat it as a fixed dataset that never evolves.",
  },

  {
    id: "cs224r-lect1-q25",
    chapter: 1,
    difficulty: "medium",
    prompt: "Which statements about neural network policies are correct?",
    options: [
      {
        text: "They can consume observations or states as input.",
        isCorrect: true,
      },
      { text: "They require full state observability.", isCorrect: false },
      { text: "They can output distributions over actions.", isCorrect: true },
      { text: "They cannot handle high-dimensional inputs.", isCorrect: false },
    ],
    explanation:
      "A neural network policy can take either a state representation or an observation history as input, depending on what information the agent has. It can output a deterministic action or a distribution over actions, and stochastic distributions are useful for exploration and behavior modeling. Full state observability is not required for using a neural policy, and handling high-dimensional inputs is one reason neural networks are central to deep reinforcement learning.",
  },

  {
    id: "cs224r-lect1-q26",
    chapter: 1,
    difficulty: "hard",
    prompt:
      "For a standard state-action trajectory \\(\\tau=(s_1,a_1,\\ldots,s_T,a_T)\\), with rewards used later in the objective, which statements about \\(p_\\theta(\\tau)\\) are correct?",
    options: [
      {
        text: "It factors into initial state, policy, and dynamics terms.",
        isCorrect: true,
      },
      { text: "It depends on the policy parameters.", isCorrect: true },
      { text: "It is independent of the environment.", isCorrect: false },
      {
        text: "Reward values affect the return or objective but are not multiplicative terms in this state-action trajectory probability.",
        isCorrect: true,
      },
    ],
    explanation:
      "The trajectory probability factors into the probability of the initial state, the policy's action probabilities, and the environment transition probabilities. Policy parameters matter because they change the action-probability terms, while the environment matters through the transition terms. Rewards are used to compute the return or objective over sampled trajectories, but in this state-action factorization they are not multiplied in as if they were transition probabilities.",
  },

  {
    id: "cs224r-lect1-q27",
    chapter: 1,
    difficulty: "medium",
    prompt: "Which statements about exploration are correct?",
    options: [
      { text: "It is necessary to discover good actions.", isCorrect: true },
      { text: "It can be enabled by stochastic policies.", isCorrect: true },
      { text: "It guarantees optimal behavior.", isCorrect: false },
      { text: "It is unnecessary once learning begins.", isCorrect: false },
    ],
    explanation:
      "Exploration gives the agent experience with actions it has not fully evaluated, which is necessary for discovering better behavior. Stochastic policies are one way to explore because they sample different actions instead of repeating a single deterministic choice. Exploration can still produce poor actions and does not guarantee optimality, but without it the agent may never gather the evidence needed to improve.",
  },

  // ============================================================
  // Q28–Q35: EXACTLY 1 TRUE
  // ============================================================

  {
    id: "cs224r-lect1-q28",
    chapter: 1,
    difficulty: "easy",
    prompt:
      "Which statement best describes the goal of reinforcement learning?",
    options: [
      { text: "Maximizing expected cumulative reward.", isCorrect: true },
      { text: "Predicting labels from fixed datasets.", isCorrect: false },
      { text: "Minimizing classification error.", isCorrect: false },
      { text: "Matching human demonstrations exactly.", isCorrect: false },
    ],
    explanation:
      "The central reinforcement learning objective is to choose behavior that maximizes expected cumulative reward over trajectories. Predicting labels and minimizing classification error describe supervised learning objectives, where the target output is supplied directly. Matching demonstrations is the goal of imitation learning in some settings, but reinforcement learning is more general because it optimizes an objective signal rather than exact copying.",
  },

  {
    id: "cs224r-lect1-q29",
    chapter: 1,
    difficulty: "medium",
    prompt: "Which statement correctly describes a value function?",
    options: [
      {
        text: "It estimates expected future reward under a policy.",
        isCorrect: true,
      },
      { text: "It specifies which action to take.", isCorrect: false },
      { text: "It defines environment dynamics.", isCorrect: false },
      { text: "It replaces the reward function.", isCorrect: false },
    ],
    explanation:
      "A value function estimates expected future return when starting from a state, or from a state-action pair, and then following a policy. It is an evaluation object, not the policy itself, although policies can use value estimates to decide which actions look promising. It also does not define the environment dynamics or replace the reward function; those are separate parts of the reinforcement learning problem.",
  },

  {
    id: "cs224r-lect1-q30",
    chapter: 1,
    difficulty: "hard",
    prompt:
      "Which statement correctly describes why reinforcement learning data is non-independent and identically distributed?",
    options: [
      { text: "Actions influence future observations.", isCorrect: true },
      { text: "Rewards are deterministic.", isCorrect: false },
      { text: "Policies are always fixed.", isCorrect: false },
      { text: "States are randomly shuffled.", isCorrect: false },
    ],
    explanation:
      "Reinforcement learning data is not independent and identically distributed because the agent's actions influence which future observations it receives. If the policy changes during learning, the data distribution can shift as the agent visits different states and tries different actions. Deterministic rewards, fixed policies, or shuffled states do not explain the core issue; the key dependence comes from the feedback loop between behavior and future data.",
  },

  {
    id: "cs224r-lect1-q31",
    chapter: 1,
    difficulty: "medium",
    prompt:
      "Which statement correctly describes a partially observable environment?",
    options: [
      {
        text: "The agent cannot directly observe the full state.",
        isCorrect: true,
      },
      { text: "The environment is deterministic.", isCorrect: false },
      { text: "Rewards are unavailable.", isCorrect: false },
      { text: "Policies are unnecessary.", isCorrect: false },
    ],
    explanation:
      "A partially observable environment gives the agent an observation that does not reveal the full underlying state. This can happen even if the environment dynamics are deterministic, because the problem is about missing information rather than randomness alone. Rewards and policies still exist in partially observable settings; the policy may just need memory or belief-state inference to act well.",
  },

  {
    id: "cs224r-lect1-q32",
    chapter: 1,
    difficulty: "hard",
    prompt:
      "Which statement correctly explains why stochastic policies are useful?",
    options: [
      { text: "They encourage exploration during learning.", isCorrect: true },
      {
        text: "They remove uncertainty from the environment.",
        isCorrect: false,
      },
      { text: "They guarantee optimal actions.", isCorrect: false },
      { text: "They eliminate the need for rewards.", isCorrect: false },
    ],
    explanation:
      "A stochastic policy samples from an action distribution, so it can try multiple behaviors instead of always taking the same action in a state. That supports exploration during learning and can also model varied behavior in demonstration data. Stochasticity in the policy does not remove uncertainty from the environment, guarantee optimal actions, or remove the need for a reward signal to define what counts as good behavior.",
  },

  {
    id: "cs224r-lect1-q33",
    chapter: 1,
    difficulty: "easy",
    prompt:
      "Which statement correctly describes an action in reinforcement learning?",
    options: [
      { text: "It is a decision chosen by the agent.", isCorrect: true },
      { text: "It is the environment’s response.", isCorrect: false },
      { text: "It is identical to a reward.", isCorrect: false },
      { text: "It represents the state of the world.", isCorrect: false },
    ],
    explanation:
      "An action is the agent's decision at a time step, such as which motor command, recommendation, or token-producing behavior to take. The environment's response is the next state or observation, and the reward is the feedback used to evaluate behavior. The state describes the world; the action is what the agent does within that world.",
  },

  {
    id: "cs224r-lect1-q34",
    chapter: 1,
    difficulty: "medium",
    prompt:
      "Which statement correctly describes discounting in reinforcement learning?",
    options: [
      {
        text: "It controls the importance of future rewards.",
        isCorrect: true,
      },
      { text: "It removes randomness from rewards.", isCorrect: false },
      { text: "It guarantees convergence.", isCorrect: false },
      { text: "It replaces value functions.", isCorrect: false },
    ],
    explanation:
      "Discounting controls how strongly future rewards count relative to immediate rewards in the return. A smaller discount factor makes the objective more focused on near-term outcomes, while a factor of 1 leaves rewards across the horizon equally weighted. Discounting does not remove randomness, guarantee convergence by itself, or replace value functions that estimate discounted future return.",
  },

  {
    id: "cs224r-lect1-q35",
    chapter: 1,
    difficulty: "hard",
    prompt:
      "Which statement correctly characterizes a Markov Decision Process?",
    options: [
      {
        text: "Future states depend only on the current state and action.",
        isCorrect: true,
      },
      { text: "Observations always equal states.", isCorrect: false },
      { text: "Rewards must be deterministic.", isCorrect: false },
      { text: "Policies cannot be stochastic.", isCorrect: false },
    ],
    explanation:
      "The defining feature of a Markov Decision Process is that the next-state distribution depends on the current state and action, not on the full past history once the state is known. Observations do not always equal states, which is why partially observable formulations are needed when the agent receives incomplete information. Rewards and policies can be stochastic in practical modeling, so determinism is not what makes a decision process Markov.",
  },
];
