import { Question } from "../../quiz";

export const cs224rLecture1IntroQuestions: Question[] = [
  // ============================================================
  // CS224R – Lecture 1: Introduction to Deep Reinforcement Learning
  // Q1–Q35
  // ============================================================

  // ============================================================
  // Introductory formulation questions
  // ============================================================

  {
    id: "cs224r-lect1-q36",
    chapter: 1,
    difficulty: "easy",
    prompt:
      "A music recommender chooses a song, observes whether the user keeps listening, and then chooses the next song. Which statements explain why this can be framed as a reinforcement learning problem?",
    options: [
      {
        text: "The recommendation is an action that can change later observations and user feedback.",
        isCorrect: true,
      },
      {
        text: "The system receives an objective signal rather than a label for the one correct song at each step.",
        isCorrect: true,
      },
      {
        text: "The data distribution can evolve because earlier recommendations affect later contexts over steps.",
        isCorrect: true,
      },
      {
        text: "The system can learn from experience rather than only from fixed labeled examples.",
        isCorrect: true,
      },
    ],
    explanation:
      "The recommender is making sequential decisions: one action affects what the user hears and how future feedback is generated. That differs from ordinary supervised learning because the data distribution can depend on the system's choices and the feedback can be an objective signal rather than a direct label.",
  },

  {
    id: "cs224r-lect1-q37",
    chapter: 1,
    difficulty: "easy",
    prompt:
      "A robot controller uses a policy written as \\(\\pi_\\theta(a \\mid s)\\). Which statements correctly distinguish the policy from the environment dynamics and reward?",
    options: [
      {
        text: "The policy selects or samples actions from the current state or observation.",
        isCorrect: true,
      },
      {
        text: "Changing policy parameters can change which trajectories the agent visits.",
        isCorrect: true,
      },
      {
        text: "The policy can be represented by a neural network that outputs action probabilities.",
        isCorrect: true,
      },
      {
        text: "The policy is distinct from both the transition model and the reward function.",
        isCorrect: true,
      },
    ],
    explanation:
      "The policy represents behavior: it maps what the agent knows to actions, often as a distribution parameterized by a neural network. The dynamics describe how the world changes after an action, and the reward function scores outcomes, so those pieces play different roles in the RL objective.",
  },

  {
    id: "cs224r-lect1-q38",
    chapter: 1,
    difficulty: "easy",
    prompt:
      "A rollout is represented as \\(\\tau=(s_1,a_1,\\ldots,s_T,a_T)\\). Which statements correctly describe this trajectory representation?",
    options: [
      {
        text: "It records the temporal sequence of states or observations and actions.",
        isCorrect: true,
      },
      {
        text: "It is generated by alternating policy action choices with environment transitions.",
        isCorrect: true,
      },
      {
        text: "It can be augmented with rewards when computing the return for the episode.",
        isCorrect: true,
      },
      {
        text: "It must be identical every time the same policy is rolled out in the same task.",
        isCorrect: false,
      },
    ],
    explanation:
      "A trajectory is the data record produced by executing a policy through time, and rewards can be attached to that record when evaluating performance. Even with the same policy, stochastic actions, stochastic dynamics, or changing initial conditions can make different rollouts differ.",
  },

  {
    id: "cs224r-lect1-q39",
    chapter: 1,
    difficulty: "medium",
    prompt:
      "A towel-hanging robot uses \\(s_t\\) to include the arm pose, towel pose, and hook pose. Which statement would be evidence that this representation is not really Markov?",
    options: [
      {
        text: "Predicting the next towel pose also requires an earlier hidden contact event that is not encoded in \\(s_t\\).",
        isCorrect: true,
      },
      {
        text: "The next state is sampled from a transition distribution rather than computed deterministically, because the world can be stochastic.",
        isCorrect: false,
      },
      {
        text: "A policy uses only the current state as input instead of receiving the complete history.",
        isCorrect: false,
      },
      {
        text: "The state-action sequence can be written as a trajectory for later learning or evaluation.",
        isCorrect: false,
      },
    ],
    explanation:
      "The Markov property says the current state and action are sufficient for predicting the next-state distribution. Stochastic dynamics and policies are compatible with that property, but an unencoded past event that still affects the future means the chosen representation is missing state information.",
  },

  {
    id: "cs224r-lect1-q40",
    chapter: 1,
    difficulty: "medium",
    prompt:
      "A self-driving system receives a current camera and LiDAR snapshot, but the snapshot alone does not reveal nearby cars' velocities. Which statements explain why observation history may be useful?",
    options: [
      {
        text: "A single observation can omit information needed to predict what happens next.",
        isCorrect: true,
      },
      {
        text: "A short history can help infer hidden variables such as velocity from changes over time.",
        isCorrect: true,
      },
      {
        text: "An observation is what the agent directly receives, even when it is not a complete state.",
        isCorrect: true,
      },
      {
        text: "A policy with memory can use several observations when the current one is partial.",
        isCorrect: true,
      },
    ],
    explanation:
      "Observations are what the agent directly receives, and they may be partial views of the true state. History can make the policy's input closer to a useful state representation, especially when velocity or other hidden variables must be inferred over time.",
  },

  {
    id: "cs224r-lect1-q41",
    chapter: 1,
    difficulty: "medium",
    prompt:
      "A robot receives reward \\(1\\) only when a towel is on a hook and \\(0\\) otherwise. Which statements correctly describe this reward design?",
    options: [
      {
        text: "It specifies the task objective without directly labeling every correct action.",
        isCorrect: true,
      },
      {
        text: "It can make early learning difficult if successful trajectories are rarely observed.",
        isCorrect: true,
      },
      {
        text: "It can depend on the state, the action, or both, depending on how the task is modeled.",
        isCorrect: true,
      },
      {
        text: "It may need demonstrations, shaping, or exploration support when success is rarely observed.",
        isCorrect: true,
      },
    ],
    explanation:
      "The reward says what outcome is desirable, not which action should be chosen at each step. A sparse 0-or-1 signal may provide little guidance until the agent sees some success, which is why demonstrations, shaping, or better exploration can matter.",
  },

  {
    id: "cs224r-lect1-q42",
    chapter: 1,
    difficulty: "hard",
    prompt:
      "For \\(p_\\theta(\\tau)=p(s_1)\\prod_t \\pi_\\theta(a_t \\mid s_t)p(s_{t+1} \\mid s_t,a_t)\\), which statements correctly connect trajectory probabilities to the RL objective?",
    options: [
      {
        text: "Policy parameters affect expected return by changing the distribution over trajectories.",
        isCorrect: true,
      },
      {
        text: "The objective averages cumulative reward over trajectories induced by policy and dynamics.",
        isCorrect: true,
      },
      {
        text: "Reward values must be multiplied into \\(p_\\theta(\\tau)\\) as transition probabilities.",
        isCorrect: false,
      },
      {
        text: "The policy is optimized as a fixed-label predictor whose outputs cannot affect later states.",
        isCorrect: false,
      },
    ],
    explanation:
      "The policy appears in the objective through the trajectory distribution: different action probabilities make different futures more or less likely. Rewards are summed along sampled trajectories to define return, but they are not themselves transition-probability factors in this state-action trajectory model.",
  },

  {
    id: "cs224r-lect1-q43",
    chapter: 1,
    difficulty: "hard",
    prompt:
      "Which statements identify source-backed reasons to use a stochastic policy rather than a deterministic mapping from state to one action?",
    options: [
      {
        text: "Sampling different actions can support exploration while learning from experience.",
        isCorrect: true,
      },
      {
        text: "A distribution over actions can model varied behavior seen in collected data.",
        isCorrect: true,
      },
      {
        text: "A stochastic policy assigns probabilities to actions rather than choosing only one fixed action.",
        isCorrect: true,
      },
      {
        text: "Generative models over actions can be useful when behavior data contains variation across demos.",
        isCorrect: true,
      },
    ],
    explanation:
      "The lecture motivates stochastic policies both for exploration and for modeling behavior that varies across people or systems. In this framing, the policy is a distribution over actions, which makes generative action models relevant for reinforcement learning and imitation learning.",
  },

  {
    id: "cs224r-lect1-q44",
    chapter: 1,
    difficulty: "hard",
    prompt:
      "Which statements correctly distinguish \\(V^\\pi(s)\\) and \\(Q^\\pi(s,a)\\) from the immediate reward function?",
    options: [
      {
        text: "\\(V^\\pi(s)\\) estimates future expected reward starting at \\(s\\) and then following \\(\\pi\\).",
        isCorrect: true,
      },
      {
        text: "\\(Q^\\pi(s,a)\\) evaluates taking \\(a\\) first and then following \\(\\pi\\).",
        isCorrect: true,
      },
      {
        text: "Both functions are simply aliases for the one-step reward \\(r(s,a)\\).",
        isCorrect: false,
      },
      {
        text: "Both functions are independent of the policy used after the current state or action is chosen.",
        isCorrect: false,
      },
    ],
    explanation:
      "Value functions summarize long-term consequences under a policy, so they are not just immediate rewards. The state value starts from a state and follows the policy, while the Q-function fixes the first action before continuing with the policy.",
  },

  // ============================================================
  // Q10–Q18: EXACTLY 3 TRUE
  // ============================================================

  {
    id: "cs224r-lect1-q10",
    chapter: 1,
    difficulty: "easy",
    prompt:
      "Which statements about supervised learning versus reinforcement learning are correct?",
    options: [
      {
        text: "Supervised learning typically uses labeled input–output pairs.",
        isCorrect: true,
      },
      {
        text: "Reinforcement learning feedback is often delayed.",
        isCorrect: true,
      },
      {
        text: "Reinforcement learning data is not independent and identically distributed.",
        isCorrect: true,
      },
      {
        text: "Supervised learning requires interaction with an environment before each training label is produced.",
        isCorrect: false,
      },
    ],
    explanation:
      "Supervised learning relies on fixed labeled datasets, while reinforcement learning depends on interaction. Actions in reinforcement learning influence future data, breaking the independent and identically distributed assumption.",
  },

  {
    id: "cs224r-lect1-q11",
    chapter: 1,
    difficulty: "medium",
    prompt: "Which statements about Markov Decision Processes are correct?",
    options: [
      {
        text: "They consist of states, actions, rewards, and dynamics.",
        isCorrect: true,
      },
      { text: "They assume the Markov property holds.", isCorrect: true },
      {
        text: "They define a probability distribution over trajectories.",
        isCorrect: true,
      },
      {
        text: "They require full observability of the environment.",
        isCorrect: false,
      },
    ],
    explanation:
      'A Markov Decision Process assumes full access to the state, but this assumption can be relaxed in partially observable settings. To reason through the choices, select the statements that match the criterion in the prompt: "They consist of states, actions, rewards, and dynamics."; "They assume the Markov property holds."; "They define a probability distribution over trajectories.". Do not select statements that miss that criterion: "They require full observability of the environment.". This contrast makes the conceptual boundary explicit instead of relying on familiar-sounding wording.',
  },

  {
    id: "cs224r-lect1-q12",
    chapter: 1,
    difficulty: "medium",
    prompt: "Which statements about observations are correct?",
    options: [
      {
        text: "They may require maintaining a history to infer the state.",
        isCorrect: true,
      },
      {
        text: "They are always equivalent to the true state.",
        isCorrect: false,
      },
      { text: "They can come from sensors or user inputs.", isCorrect: true },
      {
        text: "They can lead to partially observable problems.",
        isCorrect: true,
      },
    ],
    explanation:
      'Observations may omit important information. Using history or memory helps compensate for this partial observability. To reason through the choices, select the statements that match the criterion in the prompt: "They may require maintaining a history to infer the state."; "They can come from sensors or user inputs."; "They can lead to partially observable problems.". Do not select statements that miss that criterion: "They are always equivalent to the true state.". This contrast makes the conceptual boundary explicit instead of relying on familiar-sounding wording.',
  },

  {
    id: "cs224r-lect1-q13",
    chapter: 1,
    difficulty: "medium",
    prompt: "Which statements about trajectories are correct?",
    options: [
      {
        text: "They depend on both the policy and environment dynamics.",
        isCorrect: true,
      },
      { text: "They are deterministic given a policy.", isCorrect: false },
      { text: "They can be used as training data.", isCorrect: true },
      {
        text: "They represent experience collected by the agent.",
        isCorrect: true,
      },
    ],
    explanation:
      'Trajectories capture interaction experience. Randomness in the environment or policy means trajectories vary even under the same policy. To reason through the choices, select the statements that match the criterion in the prompt: "They depend on both the policy and environment dynamics."; "They can be used as training data."; "They represent experience collected by the agent.". Do not select statements that miss that criterion: "They are deterministic given a policy.". This contrast makes the conceptual boundary explicit instead of relying on familiar-sounding wording.',
  },

  {
    id: "cs224r-lect1-q14",
    chapter: 1,
    difficulty: "hard",
    prompt:
      "Which statements about stochasticity in reinforcement learning are correct?",
    options: [
      { text: "Environment transitions can be stochastic.", isCorrect: true },
      {
        text: "Policies can introduce randomness in action selection.",
        isCorrect: true,
      },
      { text: "Stochasticity affects expected returns.", isCorrect: true },
      { text: "Stochasticity makes learning impossible.", isCorrect: false },
    ],
    explanation:
      'Stochasticity introduces uncertainty but does not prevent learning. Algorithms explicitly account for randomness through expectations. To reason through the choices, select the statements that match the criterion in the prompt: "Environment transitions can be stochastic."; "Policies can introduce randomness in action selection."; "Stochasticity affects expected returns.". Do not select statements that miss that criterion: "Stochasticity makes learning impossible.". This contrast makes the conceptual boundary explicit instead of relying on familiar-sounding wording.',
  },

  {
    id: "cs224r-lect1-q15",
    chapter: 1,
    difficulty: "hard",
    prompt: "Which statements about discount factors are correct?",
    options: [
      {
        text: "They weight future rewards relative to immediate rewards.",
        isCorrect: true,
      },
      {
        text: "A discount factor of 1 treats all rewards equally.",
        isCorrect: true,
      },
      {
        text: "Smaller discount factors emphasize near-term rewards.",
        isCorrect: true,
      },
      {
        text: "Discount factors eliminate the need for value functions.",
        isCorrect: false,
      },
    ],
    explanation:
      'Discounting controls the importance of future outcomes. Value functions remain necessary to evaluate long-term consequences. To reason through the choices, select the statements that match the criterion in the prompt: "They weight future rewards relative to immediate rewards."; "A discount factor of 1 treats all rewards equally."; "Smaller discount factors emphasize near-term rewards.". Do not select statements that miss that criterion: "Discount factors eliminate the need for value functions.". This contrast makes the conceptual boundary explicit instead of relying on familiar-sounding wording.',
  },

  {
    id: "cs224r-lect1-q16",
    chapter: 1,
    difficulty: "medium",
    prompt:
      "Which statements about policies parameterized by neural networks are correct?",
    options: [
      {
        text: "They can process high-dimensional inputs like images.",
        isCorrect: true,
      },
      {
        text: "They can be trained using gradient-based methods.",
        isCorrect: true,
      },
      { text: "They require labeled action targets.", isCorrect: false },
      {
        text: "They are common in deep reinforcement learning.",
        isCorrect: true,
      },
    ],
    explanation:
      'Deep reinforcement learning uses neural networks to handle complex inputs. Learning is driven by rewards rather than explicit action labels. To reason through the choices, select the statements that match the criterion in the prompt: "They can process high-dimensional inputs like images."; "They can be trained using gradient-based methods."; "They are common in deep reinforcement learning.". Do not select statements that miss that criterion: "They require labeled action targets.". This contrast makes the conceptual boundary explicit instead of relying on familiar-sounding wording.',
  },

  {
    id: "cs224r-lect1-q17",
    chapter: 1,
    difficulty: "hard",
    prompt: "Which statements about value functions are correct?",
    options: [
      {
        text: "They estimate expected future reward under a policy.",
        isCorrect: true,
      },
      {
        text: "They depend on the dynamics of the environment.",
        isCorrect: true,
      },
      { text: "They can be used to improve policies.", isCorrect: true },
      { text: "They eliminate the need for exploration.", isCorrect: false },
    ],
    explanation:
      'Value functions help evaluate and improve policies but do not remove the need to explore uncertain actions. To reason through the choices, select the statements that match the criterion in the prompt: "They estimate expected future reward under a policy."; "They depend on the dynamics of the environment."; "They can be used to improve policies.". Do not select statements that miss that criterion: "They eliminate the need for exploration.". This contrast makes the conceptual boundary explicit instead of relying on familiar-sounding wording.',
  },

  {
    id: "cs224r-lect1-q18",
    chapter: 1,
    difficulty: "easy",
    prompt:
      "Which statements about reinforcement learning applications are correct?",
    options: [
      { text: "They include robotics and control tasks.", isCorrect: true },
      { text: "They include game playing.", isCorrect: true },
      { text: "They include language model post-training.", isCorrect: true },
      { text: "They are limited to simulated environments.", isCorrect: false },
    ],
    explanation:
      'Reinforcement learning is applied across many domains, including real-world systems. Simulation is common but not mandatory. To reason through the choices, select the statements that match the criterion in the prompt: "They include robotics and control tasks."; "They include game playing."; "They include language model post-training.". Do not select statements that miss that criterion: "They are limited to simulated environments.". This contrast makes the conceptual boundary explicit instead of relying on familiar-sounding wording.',
  },

  // ============================================================
  // Q19–Q27: EXACTLY 2 TRUE
  // ============================================================

  {
    id: "cs224r-lect1-q19",
    chapter: 1,
    difficulty: "easy",
    prompt:
      "Which statements correctly describe actions in reinforcement learning?",
    options: [
      { text: "They are decisions made by the agent.", isCorrect: true },
      { text: "They influence future states.", isCorrect: true },
      { text: "They are always discrete.", isCorrect: false },
      { text: "They are independent of the policy.", isCorrect: false },
    ],
    explanation:
      "Actions represent the agent’s choices and affect how the environment evolves. They may be continuous or discrete and are selected according to the policy.",
  },

  {
    id: "cs224r-lect1-q20",
    chapter: 1,
    difficulty: "medium",
    prompt:
      "Which statements about partially observable Markov decision processes are correct?",
    options: [
      {
        text: "They arise when the agent cannot observe the full state.",
        isCorrect: true,
      },
      { text: "They often require memory or belief states.", isCorrect: true },
      {
        text: "They assume the Markov property over observations.",
        isCorrect: false,
      },
      { text: "They remove the need for policies.", isCorrect: false },
    ],
    explanation:
      'Partial observability complicates decision-making. Memory or inference over hidden states helps address missing information. To reason through the choices, select the statements that match the criterion in the prompt: "They arise when the agent cannot observe the full state."; "They often require memory or belief states.". Do not select statements that miss that criterion: "They assume the Markov property over observations."; "They remove the need for policies.". This contrast makes the conceptual boundary explicit instead of relying on familiar-sounding wording.',
  },

  {
    id: "cs224r-lect1-q21",
    chapter: 1,
    difficulty: "medium",
    prompt: "Which statements about trajectories are correct?",
    options: [
      { text: "They can include both states and actions.", isCorrect: true },
      { text: "They always have fixed length.", isCorrect: false },
      { text: "They are equivalent to supervised datasets.", isCorrect: false },
      { text: "They represent sequences over time.", isCorrect: true },
    ],
    explanation:
      'Trajectories capture temporal structure, which distinguishes them from static datasets. Length can vary depending on termination conditions. To reason through the choices, select the statements that match the criterion in the prompt: "They can include both states and actions."; "They represent sequences over time.". Do not select statements that miss that criterion: "They always have fixed length."; "They are equivalent to supervised datasets.". This contrast makes the conceptual boundary explicit instead of relying on familiar-sounding wording.',
  },

  {
    id: "cs224r-lect1-q22",
    chapter: 1,
    difficulty: "hard",
    prompt: "Which statements about reward design are correct?",
    options: [
      { text: "Sparse rewards can make learning difficult.", isCorrect: true },
      { text: "Reward shaping can help guide learning.", isCorrect: true },
      { text: "Rewards must always be differentiable.", isCorrect: false },
      { text: "Rewards uniquely determine optimal actions.", isCorrect: false },
    ],
    explanation:
      'Sparse rewards provide little feedback, slowing learning. Rewards need not be differentiable and often allow multiple optimal behaviors. To reason through the choices, select the statements that match the criterion in the prompt: "Sparse rewards can make learning difficult."; "Reward shaping can help guide learning.". Do not select statements that miss that criterion: "Rewards must always be differentiable."; "Rewards uniquely determine optimal actions.". This contrast makes the conceptual boundary explicit instead of relying on familiar-sounding wording.',
  },

  {
    id: "cs224r-lect1-q23",
    chapter: 1,
    difficulty: "hard",
    prompt: "Which statements about expected return are correct?",
    options: [
      {
        text: "It averages rewards over possible trajectories.",
        isCorrect: true,
      },
      { text: "It depends on the policy.", isCorrect: true },
      { text: "It ignores stochasticity.", isCorrect: false },
      { text: "It is identical to immediate reward.", isCorrect: false },
    ],
    explanation:
      'Expected return accounts for uncertainty by averaging over outcomes. It captures long-term performance rather than immediate reward. To reason through the choices, select the statements that match the criterion in the prompt: "It averages rewards over possible trajectories."; "It depends on the policy.". Do not select statements that miss that criterion: "It ignores stochasticity."; "It is identical to immediate reward.". This contrast makes the conceptual boundary explicit instead of relying on familiar-sounding wording.',
  },

  {
    id: "cs224r-lect1-q24",
    chapter: 1,
    difficulty: "easy",
    prompt: "Which statements about reinforcement learning data are correct?",
    options: [
      { text: "It is generated through interaction.", isCorrect: true },
      {
        text: "It is independent and identically distributed.",
        isCorrect: false,
      },
      { text: "It reflects the agent’s current policy.", isCorrect: true },
      { text: "It never changes over time.", isCorrect: false },
    ],
    explanation:
      "Data in reinforcement learning depends on the policy and evolves as the policy changes. This violates the independent and identically distributed assumption.",
  },

  {
    id: "cs224r-lect1-q25",
    chapter: 1,
    difficulty: "medium",
    prompt: "Which statements about neural network policies are correct?",
    options: [
      {
        text: "They can consume observations or states as input.",
        isCorrect: true,
      },
      { text: "They require full state observability.", isCorrect: false },
      { text: "They can output distributions over actions.", isCorrect: true },
      { text: "They cannot handle high-dimensional inputs.", isCorrect: false },
    ],
    explanation:
      'Neural networks are flexible function approximators. They are widely used to handle high-dimensional sensory inputs. To reason through the choices, select the statements that match the criterion in the prompt: "They can consume observations or states as input."; "They can output distributions over actions.". Do not select statements that miss that criterion: "They require full state observability."; "They cannot handle high-dimensional inputs.". This contrast makes the conceptual boundary explicit instead of relying on familiar-sounding wording.',
  },

  {
    id: "cs224r-lect1-q26",
    chapter: 1,
    difficulty: "hard",
    prompt:
      "For a standard state-action trajectory \\(\\tau=(s_1,a_1,\\ldots,s_T,a_T)\\), with rewards used later in the objective, which statements about \\(p_\\theta(\\tau)\\) are correct?",
    options: [
      {
        text: "It factors into initial state, policy, and dynamics terms.",
        isCorrect: true,
      },
      { text: "It depends on the policy parameters.", isCorrect: true },
      { text: "It is independent of the environment.", isCorrect: false },
      {
        text: "Reward values affect the return or objective but are not multiplicative terms in this state-action trajectory probability.",
        isCorrect: true,
      },
    ],
    explanation:
      "The usual factorization multiplies the initial-state distribution, policy action probabilities, and environment transition dynamics. Rewards determine the return being optimized, but for this state-action trajectory probability they are not another multiplicative probability term; the environment still matters through the transition factors.",
  },

  {
    id: "cs224r-lect1-q27",
    chapter: 1,
    difficulty: "medium",
    prompt: "Which statements about exploration are correct?",
    options: [
      { text: "It is necessary to discover good actions.", isCorrect: true },
      { text: "It can be enabled by stochastic policies.", isCorrect: true },
      { text: "It guarantees optimal behavior.", isCorrect: false },
      { text: "It is unnecessary once learning begins.", isCorrect: false },
    ],
    explanation:
      'Exploration allows agents to gather informative experience. It does not guarantee optimality but is essential for learning. To reason through the choices, select the statements that match the criterion in the prompt: "It is necessary to discover good actions."; "It can be enabled by stochastic policies.". Do not select statements that miss that criterion: "It guarantees optimal behavior."; "It is unnecessary once learning begins.". This contrast makes the conceptual boundary explicit instead of relying on familiar-sounding wording.',
  },

  // ============================================================
  // Q28–Q35: EXACTLY 1 TRUE
  // ============================================================

  {
    id: "cs224r-lect1-q28",
    chapter: 1,
    difficulty: "easy",
    prompt:
      "Which statement best describes the goal of reinforcement learning?",
    options: [
      { text: "Maximizing expected cumulative reward.", isCorrect: true },
      { text: "Predicting labels from fixed datasets.", isCorrect: false },
      { text: "Minimizing classification error.", isCorrect: false },
      { text: "Matching human demonstrations exactly.", isCorrect: false },
    ],
    explanation:
      'Reinforcement learning optimizes long-term reward rather than immediate accuracy or label matching. To reason through the choices, select the statements that match the criterion in the prompt: "Maximizing expected cumulative reward.". Do not select statements that miss that criterion: "Predicting labels from fixed datasets."; "Minimizing classification error."; "Matching human demonstrations exactly.". This contrast makes the conceptual boundary explicit instead of relying on familiar-sounding wording.',
  },

  {
    id: "cs224r-lect1-q29",
    chapter: 1,
    difficulty: "medium",
    prompt: "Which statement correctly describes a value function?",
    options: [
      {
        text: "It estimates expected future reward under a policy.",
        isCorrect: true,
      },
      { text: "It specifies which action to take.", isCorrect: false },
      { text: "It defines environment dynamics.", isCorrect: false },
      { text: "It replaces the reward function.", isCorrect: false },
    ],
    explanation:
      'Value functions evaluate states or actions but do not directly select actions. To reason through the choices, select the statements that match the criterion in the prompt: "It estimates expected future reward under a policy.". Do not select statements that miss that criterion: "It specifies which action to take."; "It defines environment dynamics."; "It replaces the reward function.". This contrast makes the conceptual boundary explicit instead of relying on familiar-sounding wording.',
  },

  {
    id: "cs224r-lect1-q30",
    chapter: 1,
    difficulty: "hard",
    prompt:
      "Which statement correctly describes why reinforcement learning data is non-independent and identically distributed?",
    options: [
      { text: "Actions influence future observations.", isCorrect: true },
      { text: "Rewards are deterministic.", isCorrect: false },
      { text: "Policies are always fixed.", isCorrect: false },
      { text: "States are randomly shuffled.", isCorrect: false },
    ],
    explanation:
      'Because actions affect future states, data depends on past decisions and policy behavior. To reason through the choices, select the statements that match the criterion in the prompt: "Actions influence future observations.". Do not select statements that miss that criterion: "Rewards are deterministic."; "Policies are always fixed."; "States are randomly shuffled.". This contrast makes the conceptual boundary explicit instead of relying on familiar-sounding wording.',
  },

  {
    id: "cs224r-lect1-q31",
    chapter: 1,
    difficulty: "medium",
    prompt:
      "Which statement correctly describes a partially observable environment?",
    options: [
      {
        text: "The agent cannot directly observe the full state.",
        isCorrect: true,
      },
      { text: "The environment is deterministic.", isCorrect: false },
      { text: "Rewards are unavailable.", isCorrect: false },
      { text: "Policies are unnecessary.", isCorrect: false },
    ],
    explanation:
      'Partial observability arises when sensors or inputs provide incomplete information about the world. To reason through the choices, select the statements that match the criterion in the prompt: "The agent cannot directly observe the full state.". Do not select statements that miss that criterion: "The environment is deterministic."; "Rewards are unavailable."; "Policies are unnecessary.". This contrast makes the conceptual boundary explicit instead of relying on familiar-sounding wording.',
  },

  {
    id: "cs224r-lect1-q32",
    chapter: 1,
    difficulty: "hard",
    prompt:
      "Which statement correctly explains why stochastic policies are useful?",
    options: [
      { text: "They encourage exploration during learning.", isCorrect: true },
      {
        text: "They remove uncertainty from the environment.",
        isCorrect: false,
      },
      { text: "They guarantee optimal actions.", isCorrect: false },
      { text: "They eliminate the need for rewards.", isCorrect: false },
    ],
    explanation:
      'Stochastic policies allow agents to try different actions and gather informative experience. To reason through the choices, select the statements that match the criterion in the prompt: "They encourage exploration during learning.". Do not select statements that miss that criterion: "They remove uncertainty from the environment."; "They guarantee optimal actions."; "They eliminate the need for rewards.". This contrast makes the conceptual boundary explicit instead of relying on familiar-sounding wording.',
  },

  {
    id: "cs224r-lect1-q33",
    chapter: 1,
    difficulty: "easy",
    prompt:
      "Which statement correctly describes an action in reinforcement learning?",
    options: [
      { text: "It is a decision chosen by the agent.", isCorrect: true },
      { text: "It is the environment’s response.", isCorrect: false },
      { text: "It is identical to a reward.", isCorrect: false },
      { text: "It represents the state of the world.", isCorrect: false },
    ],
    explanation:
      'Actions are chosen by the agent and influence how the environment evolves. To reason through the choices, select the statements that match the criterion in the prompt: "It is a decision chosen by the agent.". Do not select statements that miss that criterion: "It is the environment’s response."; "It is identical to a reward."; "It represents the state of the world.". This contrast makes the conceptual boundary explicit instead of relying on familiar-sounding wording.',
  },

  {
    id: "cs224r-lect1-q34",
    chapter: 1,
    difficulty: "medium",
    prompt:
      "Which statement correctly describes discounting in reinforcement learning?",
    options: [
      {
        text: "It controls the importance of future rewards.",
        isCorrect: true,
      },
      { text: "It removes randomness from rewards.", isCorrect: false },
      { text: "It guarantees convergence.", isCorrect: false },
      { text: "It replaces value functions.", isCorrect: false },
    ],
    explanation:
      'Discounting reflects how much the agent values future outcomes relative to immediate ones. To reason through the choices, select the statements that match the criterion in the prompt: "It controls the importance of future rewards.". Do not select statements that miss that criterion: "It removes randomness from rewards."; "It guarantees convergence."; "It replaces value functions.". This contrast makes the conceptual boundary explicit instead of relying on familiar-sounding wording.',
  },

  {
    id: "cs224r-lect1-q35",
    chapter: 1,
    difficulty: "hard",
    prompt:
      "Which statement correctly characterizes a Markov Decision Process?",
    options: [
      {
        text: "Future states depend only on the current state and action.",
        isCorrect: true,
      },
      { text: "Observations always equal states.", isCorrect: false },
      { text: "Rewards must be deterministic.", isCorrect: false },
      { text: "Policies cannot be stochastic.", isCorrect: false },
    ],
    explanation:
      'The defining feature of a Markov Decision Process is the Markov property. Other assumptions such as determinism are not required. To reason through the choices, select the statements that match the criterion in the prompt: "Future states depend only on the current state and action.". Do not select statements that miss that criterion: "Observations always equal states."; "Rewards must be deterministic."; "Policies cannot be stochastic.". This contrast makes the conceptual boundary explicit instead of relying on familiar-sounding wording.',
  },
];
