import { Question } from "../../quiz";

export const cs224rLecture7OfflineRLQuestions: Question[] = [
  {
    id: "cs224r-lect7-q01",
    chapter: 7,
    difficulty: "easy",
    prompt:
      "Which statements describe the offline reinforcement learning setting used in the Lecture 7 slides?",
    options: [
      {
        text: "The learner receives a fixed dataset \\(\\mathcal{D}=\\{(s,a,r,s')\\}\\) before training rather than collecting fresh transitions during the update.",
        isCorrect: true,
      },
      {
        text: "The data are generated by some behavior policy \\(\\pi_\\beta\\), which may be unknown or may summarize a mixture of logging policies.",
        isCorrect: true,
      },
      {
        text: "The goal is still to learn a policy \\(\\pi_\\theta\\) with high expected return, not merely to reproduce every action in the dataset.",
        isCorrect: true,
      },
      {
        text: "The central technical difficulty is that \\(\\pi_\\theta\\) can ask the learned critic about actions that are poorly covered by \\(\\mathcal{D}\\).",
        isCorrect: true,
      },
    ],
    explanation:
      "Offline RL keeps the usual control objective but removes the online data-collection loop. That makes support mismatch central: the learned policy may prefer actions for which the fixed dataset gives little or no evidence.",
  },

  {
    id: "cs224r-lect7-q02",
    chapter: 7,
    difficulty: "easy",
    prompt:
      "Compared with online RL, which changes are introduced when training entirely from an offline dataset?",
    options: [
      {
        text: "The algorithm cannot repair a bad intermediate policy by simply rolling it out and adding its new transitions to the replay buffer.",
        isCorrect: true,
      },
      {
        text: "The distribution of training actions is tied to \\(\\pi_\\beta\\), while the policy being optimized may move toward a different \\(\\pi_\\theta\\).",
        isCorrect: true,
      },
      {
        text: "The reward labels in the dataset can still be used to distinguish better and worse behavior.",
        isCorrect: true,
      },
      {
        text: "The Bellman discount is set to \\(\\gamma=0\\), so the target collapses to \\(Q(s,a)=r(s,a)\\) because future rewards are inaccessible without online interaction.",
        isCorrect: false,
      },
    ],
    explanation:
      "Offline RL can still use rewards and bootstrapped value targets from the static transitions. What changes is the feedback loop: policy-induced distribution shift cannot be corrected by collecting new on-policy data.",
  },

  {
    id: "cs224r-lect7-q03",
    chapter: 7,
    difficulty: "medium",
    prompt:
      "In the slide's off-policy critic target, \\(Q(s,a)\\) is fit toward \\(r+\\gamma\\,\\mathbb{E}_{a'\\sim\\pi_\\theta(\\cdot\\mid s')}[Q(s',a')]\\). Why is this target risky in offline RL?",
    options: [
      {
        text: "The expectation can place probability mass on next actions \\(a'\\) that are outside or barely inside the dataset support at \\(s'\\).",
        isCorrect: true,
      },
      {
        text: "The actor can exploit accidental overestimation by selecting actions whose learned \\(Q\\)-values are high for data-poor reasons.",
        isCorrect: true,
      },
      {
        text: "The target becomes invalid whenever rewards are unobserved; with observed rewards, no distribution-shift problem remains.",
        isCorrect: false,
      },
      {
        text: "Replacing \\(\\pi_\\theta\\) with the behavior action distribution removes the relevant approximation error from \\(Q\\).",
        isCorrect: false,
      },
    ],
    explanation:
      "The dangerous term is the learned-policy expectation over next actions. Even with observed rewards, the critic can be asked to extrapolate to actions that the fixed dataset did not constrain well.",
  },

  {
    id: "cs224r-lect7-q04",
    chapter: 7,
    difficulty: "medium",
    prompt:
      "At a state \\(s\\), the dataset contains only actions \\(a_1\\) and \\(a_2\\). A learned critic estimates \\(Q(s,a_1)=4\\), \\(Q(s,a_2)=5\\), and \\(Q(s,a_3)=12\\), where \\(a_3\\) was never observed at \\(s\\). Which action best illustrates the offline-RL overestimation failure mode?",
    options: [
      {
        text: "Choosing \\(a_3\\), because a greedy policy can chase the unsupported high value.",
        isCorrect: true,
      },
      {
        text: "Choosing \\(a_2\\), because the best supported dataset action is automatically an extrapolation error.",
        isCorrect: false,
      },
      {
        text: "Choosing \\(a_1\\), because offline RL is required to imitate the most frequent action.",
        isCorrect: false,
      },
      {
        text: "Choosing no action, because a critic does not define a greedy policy in a continuous or discrete action space.",
        isCorrect: false,
      },
    ],
    explanation:
      "The slide's failure mode is not that all maximization is wrong; it is that maximization can select an unsupported action with an erroneously high value. The unsupported value can dominate the supported actions even when the data give no evidence that it is good.",
  },

  {
    id: "cs224r-lect7-q05",
    chapter: 7,
    difficulty: "easy",
    prompt:
      "Why can offline RL improve over ordinary imitation learning according to the trajectory-stitching slides?",
    options: [
      {
        text: "Reward information lets the algorithm prefer high-return behavior rather than copying low-return demonstrations equally.",
        isCorrect: true,
      },
      {
        text: "Different trajectories may contain useful subpaths that can be combined into a policy better than any one behavior rollout.",
        isCorrect: true,
      },
      {
        text: "A method can learn that \\(s_1\\to s_3\\) and \\(s_7\\to s_9\\) are both useful, then stitch them into a route from \\(s_1\\) toward \\(s_9\\).",
        isCorrect: true,
      },
      {
        text: "Imitation learning necessarily outperforms its expert once the demonstrations are filtered into \\(\\tilde{\\mathcal{D}}=\\{\\tau\\mid r(\\tau)>\\eta\\}\\).",
        isCorrect: false,
      },
    ],
    explanation:
      "The slides contrast imitation with offline RL by emphasizing reward use and trajectory stitching. Filtering or weighting helps, but ordinary imitation remains limited because it is supervised to copy data rather than solve a control problem.",
  },

  {
    id: "cs224r-lect7-q06",
    chapter: 7,
    difficulty: "medium",
    prompt:
      "Which equations match the filtered behavior cloning baseline from the slides?",
    options: [
      {
        text: "Rank trajectories by return using \\(r(\\tau)=\\sum_{(s_t,a_t)\\in\\tau} r(s_t,a_t)\\).",
        isCorrect: true,
      },
      {
        text: "Train on the retained set with \\(\\max_\\theta \\sum_{(s,a)\\in\\tilde{\\mathcal{D}}}\\log \\pi_\\theta(a\\mid s)\\).",
        isCorrect: true,
      },
      {
        text: "Retain trajectories with \\(\\tilde{\\mathcal{D}}=\\{\\tau\\mid r(\\tau)<\\eta\\}\\) so that the policy sees the hardest failures.",
        isCorrect: false,
      },
      {
        text: "Replace the supervised log-likelihood with \\(\\min_Q \\|Q-(r+\\gamma\\max_{a'}Q')\\|^2\\) before fitting the policy.",
        isCorrect: false,
      },
    ],
    explanation:
      "Filtered behavior cloning is still supervised imitation after a reward-based filtering step. The slide ranks trajectories by return, keeps the top portion or those above a threshold, and maximizes log likelihood on the filtered data.",
  },

  {
    id: "cs224r-lect7-q07",
    chapter: 7,
    difficulty: "medium",
    prompt:
      "A dataset has trajectory returns \\([-2,3,5,9,12]\\). If filtered behavior cloning keeps trajectories with \\(r(\\tau)>5\\), which retained return set matches the slide rule?",
    options: [
      {
        text: "\\(\\{9,12\\}\\)",
        isCorrect: true,
      },
      {
        text: "\\(\\{5,9,12\\}\\)",
        isCorrect: false,
      },
      {
        text: "\\(\\{-2,3,5\\}\\)",
        isCorrect: false,
      },
      {
        text: "\\(\\{3,5,9\\}\\)",
        isCorrect: false,
      },
    ],
    explanation:
      "The slide writes the filtered set with a strict inequality, \\(r(\\tau)>\\eta\\). With \\(\\eta=5\\), the trajectory of return 5 is not retained, so only 9 and 12 remain.",
  },

  {
    id: "cs224r-lect7-q08",
    chapter: 7,
    difficulty: "medium",
    prompt:
      "Which statements correctly interpret the advantage-weighted imitation objective \\(\\max_\\theta \\mathbb{E}_{s,a\\sim\\mathcal{D}}[\\log\\pi_\\theta(a\\mid s)\\exp(A(s,a))]\\)?",
    options: [
      {
        text: "The \\(\\log\\pi_\\theta(a\\mid s)\\) term is the usual behavior-cloning log-likelihood on dataset actions.",
        isCorrect: true,
      },
      {
        text: "The multiplier \\(\\exp(A(s,a))\\) increases the influence of actions estimated to be better than the state baseline.",
        isCorrect: true,
      },
      {
        text: "The objective trains on actions sampled from \\(\\mathcal{D}\\), which helps avoid directly supervising the actor on OOD actions.",
        isCorrect: true,
      },
      {
        text: "Using an exponential weight keeps all weights positive even when the advantage estimate is negative.",
        isCorrect: true,
      },
    ],
    explanation:
      "This objective is behavior cloning with a reward-sensitive weight on each supervised example. Positive advantages get large weights, negative advantages get smaller but still positive weights, and the actions remain dataset actions.",
  },

  {
    id: "cs224r-lect7-q09",
    chapter: 7,
    difficulty: "easy",
    prompt:
      "Which relationships about the advantage function are used by the Lecture 7 weighted-imitation slides?",
    options: [
      {
        text: "\\(A^\\pi(s_t,a_t)=Q^\\pi(s_t,a_t)-V^\\pi(s_t)\\).",
        isCorrect: true,
      },
      {
        text: "A positive advantage means the action is better than the policy's state-value baseline at that state.",
        isCorrect: true,
      },
      {
        text: "\\(A^\\pi(s,a)=V^\\pi(s)-Q^\\pi(s,a)\\), so better actions have more negative advantage.",
        isCorrect: false,
      },
      {
        text: "The advantage is defined for terminal states because nonterminal returns are unavailable offline.",
        isCorrect: false,
      },
    ],
    explanation:
      "The slide explicitly recalls the standard advantage definition as a Q-value minus a state value. That sign convention is what makes higher-advantage dataset actions receive larger imitation weights.",
  },

  {
    id: "cs224r-lect7-q10",
    chapter: 7,
    difficulty: "medium",
    prompt:
      "Two dataset actions at the same state have advantages \\(A_1=1.5\\) and \\(A_2=-0.5\\). Under the slide's weight \\(w=\\exp(A)\\), what is \\(w_1/w_2\\)?",
    options: [
      {
        text: "\\(e^2\\), because \\(\\exp(1.5)/\\exp(-0.5)=\\exp(2)\\).",
        isCorrect: true,
      },
      {
        text: "\\(e^1\\), because the negative advantage is clipped to \\(0\\) before computing \\(\\exp(A_1-0)\\).",
        isCorrect: false,
      },
      {
        text: "\\(2\\), because the exponential is ignored and the ratio becomes the arithmetic difference \\(1.5-(-0.5)\\).",
        isCorrect: false,
      },
      {
        text: "\\(e^{-2}\\), because the ratio is inverted as \\(\\exp(A_2-A_1)\\), making the lower-advantage action larger.",
        isCorrect: false,
      },
    ],
    explanation:
      "The exponential weight turns advantage differences into multiplicative ratios. Since \\(1.5-(-0.5)=2\\), the higher-advantage action contributes \\(e^2\\) times as much to the weighted log-likelihood.",
  },

  {
    id: "cs224r-lect7-q11",
    chapter: 7,
    difficulty: "hard",
    prompt:
      "The slides state that the advantage-weighted objective approximates a KL-constrained policy-improvement problem. Which pieces match that connection?",
    options: [
      {
        text: "The idealized update can be written as maximizing \\(\\mathbb{E}_{a\\sim\\pi(\\cdot\\mid s)}[Q(s,a)]\\) subject to a constraint such as \\(D_{KL}(\\pi\\|\\pi_\\beta)<\\epsilon\\).",
        isCorrect: true,
      },
      {
        text: "The KL constraint explains why the learned policy is encouraged to stay near the behavior distribution rather than freely maximizing unsupported Q-values.",
        isCorrect: true,
      },
      {
        text: "The exponential advantage weight behaves like a soft preference for higher-value actions inside that behavior-proximal update.",
        isCorrect: true,
      },
      {
        text: "The approximation removes the need for reward or Q estimates because \\(\\arg\\max_\\pi D_{KL}(\\pi\\|\\pi_\\beta)\\) alone ranks actions by return.",
        isCorrect: false,
      },
    ],
    explanation:
      "The point of the KL-constrained view is to improve value while keeping the new policy close to the behavior distribution. Advantage weights provide a supervised approximation to that constrained improvement, but they still require value or advantage information.",
  },

  {
    id: "cs224r-lect7-q12",
    chapter: 7,
    difficulty: "hard",
    prompt: "Which statements correctly describe the full AWR algorithm slide?",
    options: [
      {
        text: "It fits \\(\\hat V_\\phi^{\\pi_\\beta}(s_t)\\) to Monte Carlo returns such as \\(\\sum_{t'=t}^T r(s_{t'},a_{t'})\\).",
        isCorrect: true,
      },
      {
        text: "It trains the policy with weights of the form \\(\\exp((\\sum_{t'=t}^T r(s_{t'},a_{t'})-\\hat V_\\phi^{\\pi_\\beta}(s_t))/\\alpha)\\).",
        isCorrect: true,
      },
      {
        text: "It is simple and avoids querying or training on OOD actions because the actor update uses dataset actions.",
        isCorrect: true,
      },
      {
        text: "The slide lists Monte Carlo noise and weaker behavior-policy advantage estimates as limitations of this simple method.",
        isCorrect: true,
      },
    ],
    explanation:
      "AWR's value fit and policy weight use Monte Carlo returns from the dataset, and the policy is supervised on observed actions. The slide lists Monte Carlo noise as a downside, so the claim that AWR removes that noise is intentionally false despite using a plausible Q-learning-looking formula.",
  },

  {
    id: "cs224r-lect7-q13",
    chapter: 7,
    difficulty: "medium",
    prompt:
      "In the AWR policy weight \\(\\exp((G_t-\\hat V(s_t))/\\alpha)\\), suppose \\(G_t=10\\), \\(\\hat V(s_t)=7\\), and \\(\\alpha=1.5\\). Which statements are correct?",
    options: [
      {
        text: "The exponent is \\(2\\).",
        isCorrect: true,
      },
      {
        text: "The weight is \\(e^2\\), so this transition is emphasized relative to a zero-advantage transition.",
        isCorrect: true,
      },
      {
        text: "The exponent is \\(-2\\), because returns above the value baseline should be downweighted.",
        isCorrect: false,
      },
      {
        text: "The weight is exactly \\(2\\), because \\(\\exp\\) is omitted when \\(\\alpha\\neq1\\).",
        isCorrect: false,
      },
    ],
    explanation:
      "The estimated advantage is \\(10-7=3\\), and dividing by \\(\\alpha=1.5\\) gives an exponent of 2. The exponential makes the supervised example much heavier than a transition with zero estimated advantage.",
  },

  {
    id: "cs224r-lect7-q14",
    chapter: 7,
    difficulty: "hard",
    prompt:
      "A slide asks whether TD updates can estimate advantages without querying \\(Q\\) on OOD actions. If the next-action term is estimated using \\(a'\\sim\\mathcal{D}\\) at \\(s'\\), what limitation does the slide highlight?",
    options: [
      {
        text: "The resulting critic estimates values for the behavior policy underlying the data, \\(\\pi_\\beta\\), rather than the improved policy \\(\\pi_\\theta\\).",
        isCorrect: true,
      },
      {
        text: "The resulting critic becomes an exact optimal Q-function because the next actions in the target are observed.",
        isCorrect: false,
      },
      {
        text: "The update ceases to be a TD update because it contains the term \\(r+\\gamma Q(s',a')\\).",
        isCorrect: false,
      },
      {
        text: "The update queries a dense action grid in the continuous action space to estimate \\(\\pi_\\beta\\).",
        isCorrect: false,
      },
    ],
    explanation:
      "Sampling next actions from the dataset avoids explicit OOD queries, but it also ties the target to the behavior policy. The slide presents this as the motivation for IQL: can we estimate a better-than-behavior policy value while staying inside data support?",
  },

  {
    id: "cs224r-lect7-q15",
    chapter: 7,
    difficulty: "hard",
    prompt:
      "For the expectile loss \\(\\ell_2^\\lambda(x)=\\begin{cases}(1-\\lambda)x^2,&x<0\\\\ \\lambda x^2,&\\text{otherwise}\\end{cases}\\), which statements are correct?",
    options: [
      {
        text: "When \\(\\lambda=0.5\\), the two sides have equal weight and the loss reduces to a scaled squared error.",
        isCorrect: true,
      },
      {
        text: "When \\(\\lambda=0.9\\), positive residuals receive weight \\(0.9\\) and negative residuals receive weight \\(0.1\\).",
        isCorrect: true,
      },
      {
        text: "Changing \\(\\lambda\\) changes which side of the residual distribution the fitted expectile is pulled toward.",
        isCorrect: true,
      },
      {
        text: "The loss is a cross-entropy loss because the residual is inside a logarithm.",
        isCorrect: false,
      },
    ],
    explanation:
      "Expectile regression keeps a squared residual but makes it asymmetric. The parameter \\(\\lambda\\) chooses which sign of residual is penalized more heavily, so the fitted value can move above or below the mean-like fit.",
  },

  {
    id: "cs224r-lect7-q16",
    chapter: 7,
    difficulty: "hard",
    prompt:
      "Using the same expectile loss, compare \\(x=2\\) and \\(x=-2\\) when \\(\\lambda=0.25\\). Which statements are correct?",
    options: [
      {
        text: "\\(\\ell_2^{0.25}(2)=0.25\\cdot 4=1\\).",
        isCorrect: true,
      },
      {
        text: "\\(\\ell_2^{0.25}(-2)=0.75\\cdot 4=3\\).",
        isCorrect: true,
      },
      {
        text: "The negative residual is penalized three times as much as the positive residual of the same magnitude.",
        isCorrect: true,
      },
      {
        text: "At \\(x=0\\), both pieces give zero loss even though the side weights differ.",
        isCorrect: true,
      },
    ],
    explanation:
      "With \\(\\lambda=0.25\\), the positive side has weight 0.25 and the negative side has weight 0.75. Equal squared magnitudes therefore do not imply equal losses, so the equal-loss option is false even though it sounds like ordinary MSE.",
  },

  {
    id: "cs224r-lect7-q17",
    chapter: 7,
    difficulty: "hard",
    prompt:
      "Which equations match the IQL full-algorithm slide's sign convention?",
    options: [
      {
        text: "Fit \\(\\hat V\\) by minimizing \\(\\mathbb{E}_{s,a\\sim\\mathcal{D}}[\\ell_2^\\lambda(V(s)-\\hat Q(s,a))]\\), with the slide noting a small \\(\\lambda<0.5\\).",
        isCorrect: true,
      },
      {
        text: "Update \\(\\hat Q\\) toward \\(r+\\gamma\\hat V(s')\\) using a typical squared TD error on dataset transitions.",
        isCorrect: true,
      },
      {
        text: "Extract the actor with an AWR-style objective weighted by \\(\\exp((\\hat V(s)-\\hat Q(s,a))/\\alpha)\\), which downweights high-Q dataset actions.",
        isCorrect: false,
      },
      {
        text: "Fit \\(\\hat V\\) with \\(\\ell_2^\\lambda(\\hat Q(s,a)-V(s))\\) and a large \\(\\lambda>0.5\\), exactly as written in the Lecture 7 slide.",
        isCorrect: false,
      },
    ],
    explanation:
      "The slide writes the value-fit residual as \\(V(s)-\\hat Q(s,a)\\) and explicitly annotates the small-\\(\\lambda\\) choice. The Q-target \\(r+\\gamma\\hat V(s')\\) is also part of that slide, while the actor extraction uses \\(\\hat Q-\\hat V\\), not the reversed sign.",
  },

  {
    id: "cs224r-lect7-q18",
    chapter: 7,
    difficulty: "medium",
    prompt:
      "In the IQL Q-update, let \\(r=2\\), \\(\\gamma=0.9\\), and \\(\\hat V(s')=6\\). What TD target appears in the squared loss \\((Q(s,a)-(r+\\gamma\\hat V(s')))^2\\)?",
    options: [
      {
        text: "\\(7.4\\)",
        isCorrect: true,
      },
      {
        text: "\\(6.8\\)",
        isCorrect: false,
      },
      {
        text: "\\(8.0\\)",
        isCorrect: false,
      },
      {
        text: "\\(4.4\\)",
        isCorrect: false,
      },
    ],
    explanation:
      "The target is \\(2+0.9\\cdot6=7.4\\). The key IQL point is that the bootstrap uses \\(\\hat V(s')\\), avoiding a maximization or expectation over OOD next actions.",
  },

  {
    id: "cs224r-lect7-q19",
    chapter: 7,
    difficulty: "hard",
    prompt:
      "Which statements correctly explain why IQL is called an implicit policy-improvement method in the slides?",
    options: [
      {
        text: "The value fit tries to represent the best policy value within data support using an asymmetric loss rather than explicit action maximization.",
        isCorrect: true,
      },
      {
        text: "The Q-update bootstraps through \\(\\hat V(s')\\), so the critic avoids querying \\(Q(s',a')\\) for arbitrary OOD actions.",
        isCorrect: true,
      },
      {
        text: "The final actor is still trained only on actions in the dataset through the AWR-style extraction step.",
        isCorrect: true,
      },
      {
        text: "The actor and critic are optimized jointly as \\(\\min_{Q,\\theta} L_Q-\\mathbb{E}_{a\\sim\\pi_\\theta}[Q]\\) at each gradient step, which is why the method is computationally slow.",
        isCorrect: false,
      },
    ],
    explanation:
      "IQL hides policy improvement inside the value expectile and then extracts a policy with weighted supervised learning. The slides emphasize that it never needs OOD action queries, keeps actor training on data actions, and decouples actor and critic training.",
  },

  {
    id: "cs224r-lect7-q20",
    chapter: 7,
    difficulty: "medium",
    prompt:
      "Which statements are part of the slide-level contrast between AWR and IQL?",
    options: [
      {
        text: "AWR uses Monte Carlo returns for its value/advantage estimate, which the slide lists as noisy.",
        isCorrect: true,
      },
      {
        text: "IQL replaces the Monte Carlo-only estimate with TD-style critic learning while avoiding OOD action queries.",
        isCorrect: true,
      },
      {
        text: "AWR's estimated advantage is tied to the behavior policy and can be weaker than the learned policy's advantage.",
        isCorrect: true,
      },
      {
        text: "IQL removes the need for a value function by training a pure behavior-cloning actor on the full trajectory set.",
        isCorrect: false,
      },
    ],
    explanation:
      "The AWR slide explicitly lists Monte Carlo noise and behavior-policy advantage estimates as downsides. IQL is introduced as a TD-based way to estimate a better supported value without querying OOD actions, not as a value-free behavior cloning method.",
  },

  {
    id: "cs224r-lect7-q21",
    chapter: 7,
    difficulty: "hard",
    prompt:
      "The first CQL slide adds \\(\\alpha\\mathbb{E}_{s\\sim\\mathcal{D},a\\sim\\mu(\\cdot\\mid s)}[Q(s,a)]\\) to a standard critic loss. Which interpretations are correct?",
    options: [
      {
        text: "Because the objective minimizes over \\(Q\\), a positive \\(\\alpha\\) term penalizes large Q-values under the auxiliary action distribution \\(\\mu\\).",
        isCorrect: true,
      },
      {
        text: "The max over \\(\\mu\\) makes the penalty focus on actions that the current critic rates highly.",
        isCorrect: true,
      },
      {
        text: "The added term requires an explicit parametric model \\(\\hat\\pi_\\beta(a\\mid s)\\) and weights actions by \\(1/\\hat\\pi_\\beta(a\\mid s)\\) before it can discourage overestimation.",
        isCorrect: false,
      },
      {
        text: "The added term pushes Q-values upward because minimizing \\(+\\alpha\\mathbb{E}[Q(s,a)]\\) is the same as maximizing \\(Q\\).",
        isCorrect: false,
      },
    ],
    explanation:
      "In a minimization over \\(Q\\), adding expected \\(Q\\) under adversarially chosen actions makes high values expensive. The method is conservative because it discourages overestimated actions, especially where the critic lacks data support.",
  },

  {
    id: "cs224r-lect7-q22",
    chapter: 7,
    difficulty: "medium",
    prompt:
      "What does the CQL slide claim can be shown for sufficiently large \\(\\alpha\\) in the simple conservative objective?",
    options: [
      {
        text: "\\(\\hat Q^\\pi\\le Q^\\pi\\), meaning the learned critic is a conservative lower estimate.",
        isCorrect: true,
      },
      {
        text: "\\(\\hat Q^\\pi\\ge Q^\\pi\\), meaning the learned critic intentionally overestimates the evaluated actions.",
        isCorrect: false,
      },
      {
        text: "\\(\\pi_\\theta=\\pi_\\beta\\), meaning no policy improvement can occur.",
        isCorrect: false,
      },
      {
        text: "\\(\\gamma=1\\), meaning discounting is removed from the Bellman target.",
        isCorrect: false,
      },
    ],
    explanation:
      "The slide presents conservatism as a lower-bound property when the penalty is strong enough. That lower estimate is meant to counter the offline-RL tendency to overvalue unsupported actions.",
  },

  {
    id: "cs224r-lect7-q23",
    chapter: 7,
    difficulty: "hard",
    prompt:
      "Which statements correctly distinguish the later CQL guarantee from a pointwise lower-bound guarantee?",
    options: [
      {
        text: "After adding the dataset-action term, the slide says it is no longer guaranteed that \\(\\hat Q^\\pi(s,a)\\le Q^\\pi(s,a)\\) for every individual \\((s,a)\\).",
        isCorrect: true,
      },
      {
        text: "The slide instead gives an expectation guarantee over actions sampled from \\(\\pi(a\\mid s)\\) for states in the dataset.",
        isCorrect: true,
      },
      {
        text: "The dataset-action term \\(-\\alpha\\mathbb{E}_{(s,a)\\sim\\mathcal{D}}[Q(s,a)]\\) pushes up values on observed data actions.",
        isCorrect: true,
      },
      {
        text: "The expectation bound is over states sampled from an online rollout buffer collected by the learned policy.",
        isCorrect: false,
      },
    ],
    explanation:
      "The refined objective balances pushing down high values under sampled actions with preserving or pushing up values on dataset actions. The guarantee shown on the slide is distributional over dataset states, not a pointwise inequality for every state-action pair.",
  },

  {
    id: "cs224r-lect7-q24",
    chapter: 7,
    difficulty: "hard",
    prompt:
      "Which terms belong to the CQL objective shown after adding the data-action correction?",
    options: [
      {
        text: "A standard critic squared Bellman error on \\((s,a,s')\\sim\\mathcal{D}\\).",
        isCorrect: true,
      },
      {
        text: "A positive conservative term \\(+\\alpha\\mathbb{E}_{s\\sim\\mathcal{D},a\\sim\\mu(\\cdot\\mid s)}[Q(s,a)]\\).",
        isCorrect: true,
      },
      {
        text: "A negative dataset-action term \\(-\\alpha\\mathbb{E}_{(s,a)\\sim\\mathcal{D}}[Q(s,a)]\\).",
        isCorrect: true,
      },
      {
        text: "An entropy regularizer \\(R(\\mu)\\) used when computing the inner maximization.",
        isCorrect: true,
      },
    ],
    explanation:
      "The full slide includes the Bellman error, the conservative penalty, the dataset-action correction, and a regularizer for the auxiliary distribution. These pieces together define the practical CQL loss used before the policy update.",
  },

  {
    id: "cs224r-lect7-q25",
    chapter: 7,
    difficulty: "hard",
    prompt:
      "With the max-entropy choice \\(R(\\mu)=\\mathbb{E}_{s\\sim\\mathcal{D}}[\\mathcal{H}(\\mu(\\cdot\\mid s))]\\), which statements match the CQL slide?",
    options: [
      {
        text: "The optimal auxiliary distribution satisfies \\(\\mu(a\\mid s)\\propto\\exp(Q(s,a))\\).",
        isCorrect: true,
      },
      {
        text: "The inner expected-Q term can be computed as a log-sum-exp, \\(\\log\\sum_a\\exp(Q(s,a))\\), for discrete actions.",
        isCorrect: true,
      },
      {
        text: "The slide says one must construct and sample \\(\\mu\\) directly before computing the penalty.",
        isCorrect: false,
      },
      {
        text: "The entropy choice replaces the Bellman error with supervised behavior-cloning loss.",
        isCorrect: false,
      },
    ],
    explanation:
      "The max-entropy regularized maximization yields a softmax-like auxiliary distribution and a log-sum-exp value. The method still contains the critic loss; the entropy device is for computing the conservative penalty, not for turning CQL into behavior cloning.",
  },

  {
    id: "cs224r-lect7-q26",
    chapter: 7,
    difficulty: "medium",
    prompt:
      "For a discrete state with critic values \\(Q(s,a_1)=0\\) and \\(Q(s,a_2)=1\\), what is the log-sum-exp term \\(\\log(\\exp(Q(s,a_1))+\\exp(Q(s,a_2)))\\)?",
    options: [
      {
        text: "\\(\\log(1+e)\\), approximately \\(1.31\\).",
        isCorrect: true,
      },
      {
        text: "\\(1\\), because \\(\\log\\sum_a\\exp(Q(s,a))\\) equals \\(\\max_a Q(s,a)\\) exactly in this example.",
        isCorrect: false,
      },
      {
        text: "\\(0.5\\), because the term is the arithmetic mean \\((Q(s,a_1)+Q(s,a_2))/2\\).",
        isCorrect: false,
      },
      {
        text: "\\(e\\), because the outer \\(\\log\\) is omitted and the term becomes \\(\\sum_a\\exp(Q(s,a))\\).",
        isCorrect: false,
      },
    ],
    explanation:
      "The CQL slide's max-entropy form produces a log of a sum of exponentials. For values 0 and 1, that is \\(\\log(1+e)\\), which is above the maximum but close enough to act as a smooth max.",
  },

  {
    id: "cs224r-lect7-q27",
    chapter: 7,
    difficulty: "medium",
    prompt: "Which statements match the CQL policy-update slide?",
    options: [
      {
        text: "For discrete actions, the policy can be the greedy policy that assigns probability 1 to an action in \\(\\arg\\max_a\\hat Q^\\pi(s,a)\\).",
        isCorrect: true,
      },
      {
        text: "For continuous actions, the actor can ascend \\(\\nabla_\\theta\\mathbb{E}_{s\\sim\\mathcal{D},a\\sim\\pi_\\theta(\\cdot\\mid s)}[\\hat Q^\\pi(s,a)]\\).",
        isCorrect: true,
      },
      {
        text: "The algorithm alternates updating \\(\\hat Q^\\pi\\) with \\(L_{CQL}\\) and then updating \\(\\pi\\).",
        isCorrect: true,
      },
      {
        text: "The policy update is forbidden in offline RL, so CQL stops after fitting the conservative critic.",
        isCorrect: false,
      },
    ],
    explanation:
      "CQL is still a control algorithm: after fitting a conservative critic, it updates a policy. The slide distinguishes the direct greedy update for discrete actions from an actor-gradient update for continuous actions.",
  },

  {
    id: "cs224r-lect7-q28",
    chapter: 7,
    difficulty: "hard",
    prompt:
      "A CQL loss at one dataset state contains the conservative contrast \\(\\alpha[\\log\\sum_a e^{Q(s,a)}-Q(s,a_D)]\\). If \\(\\alpha=2\\), \\(Q(s,a_1)=0\\), \\(Q(s,a_2)=1\\), and the dataset action is \\(a_D=a_2\\), which statements are correct?",
    options: [
      {
        text: "The contrast is \\(2[\\log(1+e)-1]\\).",
        isCorrect: true,
      },
      {
        text: "The contrast is positive because \\(\\log(1+e)>1\\).",
        isCorrect: true,
      },
      {
        text: "The subtraction of \\(Q(s,a_D)\\) is the term that avoids pushing down the dataset action as aggressively as unsupported high-value actions.",
        isCorrect: true,
      },
      {
        text: "If the dataset action were \\(a_1\\), the contrast would be \\(2[\\log(1+e)-0]\\), which is larger for these numbers.",
        isCorrect: true,
      },
    ],
    explanation:
      "The log-sum-exp term penalizes high values over actions, while subtracting the dataset action value preserves support actions. With \\(a_D=a_2\\), the arithmetic is \\(2[\\log(1+e)-1]\\); if the lower-valued action were the data action, the subtraction would be smaller and the penalty larger.",
  },

  {
    id: "cs224r-lect7-q29",
    chapter: 7,
    difficulty: "hard",
    prompt:
      "Which pairs correctly match an offline-RL method from the lecture to its main mechanism?",
    options: [
      {
        text: "Filtered behavior cloning: rank trajectories by return, keep high-return data, then maximize supervised log likelihood.",
        isCorrect: true,
      },
      {
        text: "IQL: use expectile value fitting and AWR-style extraction to avoid explicit OOD action maximization.",
        isCorrect: true,
      },
      {
        text: "CQL: remove the critic and use unconditional behavior cloning, keeping Q-values out of the objective.",
        isCorrect: false,
      },
      {
        text: "AWR: intentionally sample random OOD actions and clone whichever has the largest current Q-value.",
        isCorrect: false,
      },
    ],
    explanation:
      "Filtered BC and IQL are correctly matched in the first two options. CQL remains a critic-based method whose conservative objective contains Q-values, so describing it as critic-free unconditional cloning contradicts the slide.",
  },

  {
    id: "cs224r-lect7-q30",
    chapter: 7,
    difficulty: "medium",
    prompt:
      "According to the lecture summary, what is the basic reason ordinary off-policy algorithms can fail in offline RL?",
    options: [
      {
        text: "They can overestimate Q-values under the distribution shift between \\(\\pi_\\beta\\) and \\(\\pi_\\theta\\), then optimize the policy toward those errors.",
        isCorrect: true,
      },
      {
        text: "They represent rewards as unavailable because the dataset is assumed to contain states and actions but no reward labels.",
        isCorrect: false,
      },
      {
        text: "They underfit because the Bellman equation is treated as unevaluable on logged transitions.",
        isCorrect: false,
      },
      {
        text: "They must set \\(\\pi_\\theta=\\pi_\\beta\\), so there is no policy-improvement step to analyze.",
        isCorrect: false,
      },
    ],
    explanation:
      "The summary slide names overestimated Q-values caused by the shift between behavior and learned policies as the central challenge. The static dataset has rewards and transitions, but it does not cover every action the learned policy may want to evaluate.",
  },

  {
    id: "cs224r-lect7-q31",
    chapter: 7,
    difficulty: "medium",
    prompt:
      "Which statements align with the algorithm-selection slide for purely offline training?",
    options: [
      {
        text: "Filtered behavior cloning is described as a good first approach.",
        isCorrect: true,
      },
      {
        text: "IQL is presented as useful when trajectory stitching is needed while remaining explicitly constrained to data support.",
        isCorrect: true,
      },
      {
        text: "CQL is described as having essentially one key hyperparameter.",
        isCorrect: true,
      },
      {
        text: "Vanilla off-policy actor-critic is recommended as the safest default because OOD actions improve exploration offline.",
        isCorrect: false,
      },
    ],
    explanation:
      "The selection slide suggests filtered BC as a baseline, IQL for support-constrained stitching, and CQL as a conservative method with a relatively simple hyperparameter story. It does not recommend unconstrained vanilla off-policy actor-critic as the offline default.",
  },

  {
    id: "cs224r-lect7-q32",
    chapter: 7,
    difficulty: "easy",
    prompt:
      "Which statements appear in the lecture's high-level summary of approaches to offline RL?",
    options: [
      {
        text: "One approach is filtered or weighted imitation, which uses return thresholds or weights such as \\(\\exp(A(s,a))\\) while staying close to dataset actions.",
        isCorrect: true,
      },
      {
        text: "One approach is to implicitly constrain the policy to \\(\\pi_\\beta\\) by only supervising on actions in the data.",
        isCorrect: true,
      },
      {
        text: "One approach is to construct a conservative objective that penalizes Q-values with terms such as \\(+\\alpha\\mathbb{E}[Q(s,a)]\\).",
        isCorrect: true,
      },
      {
        text: "Offline RL can use trajectory stitching, for example composing supported subpaths like \\(s_1\\to s_3\\) and \\(s_7\\to s_9\\), to improve over simple imitation learning.",
        isCorrect: true,
      },
    ],
    explanation:
      "These are the main categories and takeaways on the summary slide. The lecture ties them together through the same core difficulty: policy improvement must avoid exploiting unsupported overestimated values.",
  },

  {
    id: "cs224r-lect7-q33",
    chapter: 7,
    difficulty: "hard",
    prompt:
      "A practitioner has an offline dataset and plans to fine-tune online later. Which statements are consistent with the final algorithm-selection slide?",
    options: [
      {
        text: "IQL is described as especially performant for offline pretraining followed by online fine-tuning.",
        isCorrect: true,
      },
      {
        text: "A conservative or support-constrained offline stage can provide a better initialization before interaction resumes.",
        isCorrect: true,
      },
      {
        text: "The slide says filtered behavior cloning is discarded because it fails as a baseline.",
        isCorrect: false,
      },
      {
        text: "The slide says CQL is left aside because it has zero tunable hyperparameters.",
        isCorrect: false,
      },
    ],
    explanation:
      "The deck distinguishes pure offline use from offline pretraining plus online fine-tuning and highlights IQL in the latter case. That does not make filtered BC useless as a baseline or CQL impossible to tune.",
  },

  {
    id: "cs224r-lect7-q34",
    chapter: 7,
    difficulty: "medium",
    prompt:
      "Suppose a logged dataset combines trajectories from several policies, so the behavior policy is better viewed as an unknown mixture \\(\\pi_\\beta\\). What is the safest lecture-consistent interpretation?",
    options: [
      {
        text: "Offline algorithms should treat the data support induced by \\(\\pi_\\beta\\) as a constraint or source of conservatism, even if \\(\\pi_\\beta\\) is not explicitly known.",
        isCorrect: true,
      },
      {
        text: "The mixture makes the offline problem identical to online RL because \\(\\pi_\\beta(a\\mid s)>0\\) has roughly uniform coverage across the action set.",
        isCorrect: false,
      },
      {
        text: "Unknown \\(\\pi_\\beta\\) prevents using rewards \\(r(s,a)\\), so unconditional action-frequency cloning \\(\\max_\\theta\\sum_a\\log\\pi_\\theta(a)\\) is the available objective.",
        isCorrect: false,
      },
      {
        text: "The learned policy should maximize Q-values outside the mixture support because \\(a\\notin\\mathrm{supp}(\\pi_\\beta(\\cdot\\mid s))\\) gives the least biased estimates.",
        isCorrect: false,
      },
    ],
    explanation:
      "The lecture uses \\(\\pi_\\beta\\) as the behavior distribution underlying the data, not as a guarantee that every action is covered. Even when the behavior policy is implicit, support and conservatism remain the key design constraints.",
  },

  {
    id: "cs224r-lect7-q35",
    chapter: 7,
    difficulty: "hard",
    prompt:
      "Which integrated explanation best connects the lecture's methods, equations, and failure mode?",
    options: [
      {
        text: "Filtered BC and AWR avoid OOD action queries by cloning dataset actions, but add return or advantage information so higher-value data influence the policy more.",
        isCorrect: true,
      },
      {
        text: "IQL uses expectile value fitting and \\(r+\\gamma\\hat V(s')\\) targets to estimate improved supported values without maximizing over arbitrary next actions.",
        isCorrect: true,
      },
      {
        text: "CQL makes high unsupported Q-values costly through conservative penalties while preserving values on dataset actions through the data correction term.",
        isCorrect: true,
      },
      {
        text: "The three families solve offline RL by exactly reconstructing \\(\\pi_\\beta\\), which eliminates the need for reward labels and trajectory stitching.",
        isCorrect: false,
      },
    ],
    explanation:
      "The methods differ, but they respond to the same overestimation and support-mismatch problem. Reward-weighted imitation, implicit policy constraints, and conservative Q objectives all use the logged data while trying to avoid policy improvement that is driven by unsupported value errors.",
  },
];
